 dotnet package update  Microsoft.AspNetCore.Authentication.JwtBearer 
 dotnet package update  Microsoft.AspNetCore.Identity.EntityFrameworkCore 
 dotnet package update  Microsoft.AspNetCore.Identity.UI 
 dotnet package update  Microsoft.AspNetCore.Mvc.Testing 
 dotnet package update  Microsoft.AspNetCore.Mvc.ViewFeatures 
 dotnet package update  Microsoft.AspNetCore.OpenApi 
 dotnet package update  Microsoft.AspNetCore.TestHost 
 dotnet package update  Microsoft.EntityFrameworkCore 
 dotnet package update  Microsoft.EntityFrameworkCore.InMemory 
 dotnet package update  Microsoft.EntityFrameworkCore.Relational 
 dotnet package update  Microsoft.EntityFrameworkCore.Sqlite 
 dotnet package update  Microsoft.EntityFrameworkCore.SqlServer 
 dotnet package update  Microsoft.EntityFrameworkCore.Tools
 dotnet package update  Microsoft.Extensions.Logging 
 dotnet package update  Microsoft.SyndicationFeed.ReaderWriter
 dotnet package update  Microsoft.VisualStudio.Web.CodeGeneration.Design 
 dotnet package update  Swashbuckle.AspNetCore 
 dotnet package update  System.ServiceModel.Syndication 
